== Datentransformation
=== vom Erfassungssystem zum Geodatenmodell
Vor der Überführung der Daten ins neue kantonalen Geodatenmodell wurden die Informationen zu den Waldfeststellungen in verschiedenen Dateien gehalten. Diese waren:

* **Waldfeststellungen.accdb:** MS Access-Datenbank mit Angaben zu den Waldfeststellungen, Status und Parzelleninformationen; geometrielos
* **Waldgrenze_Linie.gpkg:** Geopackage mit den für die WebGIS-Publikaiton aufbereiteten Geometrien der Waldgrenzen; als Quelle dient die Datei **WaldgrenzenKtSZ.gpkg**
* **Waldgrenze_Wirkbereich.gpkg:** Geopackage mit den für die WebGIS-Publikaiton aufbereiteten Geometrien der Wirkflächen; als Quelle dient die Datei **WaldgrenzenKtSZ_Wirkbereich.gpkg**
* **WaldgrenzenKtSZ_ersetzt.gpkg:** Geopackage mit Waldgrenzen, welche ersetzt wurden

Das kantonale Geodatenmodell umfasst auch die Stockgrenzen. Als Datenquelle dient der im WebGIS publizierte Datensatz

* **Stockgrenze**

Diese fünf Datensätze bilden den Input für die Datenübernahme ins kantonale Geodatenmodell.

==== Heruasforderungen
In den ursprünglichen Daten wurden sämtliche Informationen zu Waldfeststellungen erfasst; auch von Waldfeststellungen, welche nicht verfügt wurden (Status 9). Von diesen Waldgrenzen sind zwar sämtliche Informationen vorhanden, sie werden jedoch nicht veröffentlicht. Damit auch diese Daten übernommen werden könnne, wird ein neuer Verfahrenstyp "intern" geschaffen. Er dient dazu, alle bestehenden Informationen verlustfrei zu migrieren. Zudem sollen die Waldgrenzen, welche dem Verfahrenstyp "intern" zugeordnet sind, NICHT ins WebGIS publiziert werden.
