== Datentransformation
=== Transformation vom Erfassungssystem zum Geodatenmodell
Vor der Überführung der Daten ins neue kantonalen Geodatenmodell wurden die Informationen zu den Waldfeststellungen in verschiedenen Dateien gehalten. Diese waren:

* **Waldfeststellungen.accdb:** MS Access-Datenbank mit Angaben zu den Waldfeststellungen, Status und Parzelleninformationen; geometrielos
* **Waldgrenze_Linie.gpkg:** Geopackage mit den für die WebGIS-Publikaiton aufbereiteten Geometrien der Waldgrenzen; als Quelle dient die Datei **WaldgrenzenKtSZ.gpkg**
* **Waldgrenze_Wirkbereich.gpkg:** Geopackage mit den für die WebGIS-Publikaiton aufbereiteten Geometrien der Wirkflächen; als Quelle dient die Datei **WaldgrenzenKtSZ_Wirkbereich.gpkg**
* **WaldgrenzenKtSZ_ersetzt.gpkg:** Geopackage mit Waldgrenzen, welche ersetzt wurden

Das kantonale Geodatenmodell umfasst auch die Stockgrenzen. Als Datenquelle dient der im WebGIS publizierte Datensatz

* **Stockgrenze**

Diese fünf Datensätze bilden den Input für die Datenübernahme ins kantonale Geodatenmodell.

==== Details zum Waldfeststellungs-Status
**Attributbezeichnung**
Access-Formular: WFStatus
Access-Tabelle: Waldfeststellungen.WF_Status

**Wertebereiche**
[cols=3*,options="header"]
|===
| Code | Bezeichnung | Regel für die Datenübernahme
| 0
| provisorisch, noch nicht verfügt (ÖREB: "laufende Änderung")
| Die Daten werden übernommen. Das Begründungsverfahren weist den Status "eingeleitet" auf. Dadurch wird angezeigt, dass das Verfahren angestossen, jedoch noch nicht abgeschlossen ist.
| 1
| verfügt (ÖREB: "in Kraft")
| Die Daten werden übernommen. Das Begründungsverfahren ist abgeschlossen.
| 2
| ersetzt
| Die Daten werden übernommen. Das Begründungsverfahren wie auch das Aufhebungsverfahren sind abgeschlossen.
| 3
| altrechtlich
| Die Daten werden übernommen. Das Begründungsverfahren ist abgeschlossen. In die Bemerkung wird der Satz "altrechtliche Festsetzung" eingetragen.
| 4
| brieflich
| Die Daten werden übernommen. Das Begründungsverfahren ist abgeschlossen. Briefliche Festlegungen sind Abmachungen zwischen dem Amt und den Betroffenen, in welchen der Waldgrenzverlauf festgehalten wird. Die Daten sind intern und bleiben unveröffentlicht. Daher wird dem brieflichen Waldfeststellungsstaus das Leitverfahren "intern" zugeordnet. Waldgrenzen, die dem internen Leitverfahren zugeordnet sind, bleiben intern und werden nicht veröffentlicht. +
Folgende Werte werden ins Bemerkungsfeld eingetragen: `+Waldfeststellungen.Verfügungsdatum+` (=Versanddatum des Briefes) und `+Waldfeststellungen.VerfügungsNr+`. +
Bei internen Verfahren bleibt das Verfügungsdatum leer.
| 5
| verfügt (ausserhalb der Bauzone)
| Die Daten werden übernommen. Das Begründungsverfahren ist abgeschlossen.
| 9
| nicht verfügt
| Die Daten werden übernommen. Das Begründungsverfahren ist abgeschlossen und erhält den Status "intern".
|===

Zum Status 3 ("altrechtlich"), sind keine Daten vorhanden. Er bleibt in der oben aufgeführten Zusammenstellung unberücksichtigt.
